import Base
import ./LAWS.bend as Laws

def Laws.air_above_surface():
  {==}

def Laws.surface_is_grass():
  {==}

def Laws.known_tree_wood():
  {==}

def Laws.known_tree_leaf():
  {==}

def Laws.beach_is_sand():
  {==}

def Laws.sea_surface_is_water():
  {==}

def Laws.cave_is_air():
  {==}

def Laws.known_coal_ore():
  {==}

def Laws.known_iron_ore():
  {==}

def Laws.known_diamond_ore():
  {==}

def Laws.known_village_furnace():
  {==}
