import Base
import ./LAWS.bend as Laws

def Laws.air_above_surface():
  {==}

def Laws.surface_is_grass():
  {==}

def Laws.known_tree_wood():
  {==}

def Laws.known_tree_leaf():
  {==}

def Laws.fall_is_safe_within_three_blocks():
  {==}

def Laws.fall_costs_one_per_extra_block():
  {==}

def Laws.damage_saturates_at_zero():
  {==}

def Laws.heal_caps_at_max_health():
  {==}

def Laws.hunger_caps_at_max():
  {==}

def Laws.zero_health_is_dead():
  {==}

def Laws.hardcore_takes_damage():
  {==}

def Laws.creative_takes_no_damage():
  {==}

def Laws.pig_is_weak():
  {==}

def Laws.zombie_is_tough():
  {==}

def Laws.zombie_hurts_pig_does_not():
  {==}

def Laws.pig_is_passive():
  {==}

def Laws.zombie_is_hostile():
  {==}

def Laws.zombies_burn_in_daylight():
  {==}
